spring:
 datasource:
   trade:
     url:jdbc:h2:mem:trade;DB_CLOSE_DELAY=-1
     driverClassName:org.h2.Driver
     username:sa
     password:password
   refdata:
     url:jdbc:h2:mem:refdata;DB_CLOSE_DELAY=-1
     driverClassName:org.h2.Driver
     username:sa
     password:password









